development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
   adapter: sqlite3
   database: db/development.sqlite3
   pool: 5
   timeout: 5000

production:
  adapter: mysql2
  database: cloudweb_production
  pool: 5
  timeout: 5000
  user: "root"
  password: "W0lver1ne"
